"""Optional Dududa 2.0 social policy assets.

Importing this package does not import AstrBot; framework loading is isolated
to :mod:`.main` so the pure policy and storage APIs remain easy to test.
"""

from .policy import (
    DEFAULT_KEYWORD_RULES,
    ComplimentSignal,
    ComplimentTarget,
    KeywordMatch,
    KeywordRule,
    MoodSeverity,
    MoodSignal,
    SleepLog,
    SleepSummary,
    SocialFeature,
    SocialPolicyConfig,
    SocialPolicyError,
    SocialScope,
    UserPair,
    VoteState,
    VoteTransition,
    aggregate_sleep,
    append_sleep_log,
    apply_vote_action,
    birthday_matches,
    canonical_pair,
    classify_compliment,
    classify_mood,
    make_sleep_log,
    match_keyword,
    parse_birthday,
    rank_interactions,
    record_interaction,
)
from .storage import SCHEMA_VERSION, SocialStateStore

__all__ = [
    "DEFAULT_KEYWORD_RULES",
    "SCHEMA_VERSION",
    "ComplimentSignal",
    "ComplimentTarget",
    "KeywordMatch",
    "KeywordRule",
    "MoodSeverity",
    "MoodSignal",
    "SleepLog",
    "SleepSummary",
    "SocialFeature",
    "SocialPolicyConfig",
    "SocialPolicyError",
    "SocialScope",
    "SocialStateStore",
    "UserPair",
    "VoteState",
    "VoteTransition",
    "aggregate_sleep",
    "append_sleep_log",
    "apply_vote_action",
    "birthday_matches",
    "canonical_pair",
    "classify_compliment",
    "classify_mood",
    "make_sleep_log",
    "match_keyword",
    "parse_birthday",
    "rank_interactions",
    "record_interaction",
]
