"""Provider-neutral model selection and routing contracts."""

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .admission import InMemoryModelAdmissionController
    from .estimation import ConservativeModelInvocationEstimator, ModelTokenPricing
    from .registry import (
        InMemoryModelOperationalStateRegistry,
        InMemoryModelRoutingRegistry,
    )
    from .router import StaticModelRouter
    from .tiering import (
        DeterministicModelTierPolicy,
        FixedPerceptionBootstrapTierPolicy,
    )

from .contracts import (
    AdmissionDisposition,
    EndpointAdmissionRequest,
    EndpointAdmissionResult,
    EndpointCapacityLease,
    EndpointCapacityReceipt,
    EndpointHealthStatus,
    EndpointLoadSnapshot,
    EndpointRejection,
    EndpointRouteCandidatePlan,
    EndpointTrafficPolicy,
    LoadCounterScope,
    ModelCapabilities,
    ModelEndpointDescriptor,
    ModelEndpointHealth,
    ModelEndpointRef,
    ModelFailureKind,
    ModelInput,
    ModelInputModality,
    ModelInputPart,
    ModelInvocationEstimate,
    ModelOperationalSnapshot,
    ModelOutputModality,
    ModelPrivacyPolicy,
    ModelProcessingBoundary,
    ModelProcessingReceipt,
    ModelProviderDescriptor,
    ModelProviderHealth,
    ModelRequest,
    ModelResponse,
    ModelRetentionMode,
    ModelRole,
    ModelTier,
    ModelUsage,
    ProviderRequest,
    ProviderResponse,
    ReasoningDepth,
    ReasoningProfile,
    RouteAttempt,
    RouteAttemptKind,
    RouteDecision,
    RouteHint,
    SafetyAnnotation,
    StaleSnapshotPolicy,
    StructuredOutputSupport,
)
from .digests import (
    bootstrap_tier_policy_definition_digest,
    bootstrap_tier_decision_digest,
    bootstrap_tier_selection_fingerprint,
    endpoint_admission_request_digest,
    endpoint_admission_result_digest,
    endpoint_capacity_receipt_digest,
    model_endpoint_descriptor_digest,
    model_invocation_estimate_digest,
    model_invocation_estimate_fingerprint,
    model_operational_snapshot_digest,
    model_request_digest,
    model_request_fingerprint,
    model_route_policy_digest,
    provider_request_digest,
    route_decision_digest,
    route_plan_fingerprint,
    routing_catalog_digest,
    task_complexity_assessment_digest,
    task_complexity_assessment_fingerprint,
    tier_authority_digest,
    tier_decision_digest,
    tier_policy_definition_digest,
    tier_selection_context_digest,
    tier_selection_fingerprint,
)
from .errors import ModelInvocationError, ModelProviderError, model_error_info
from .policy import (
    BootstrapTierDecision,
    BootstrapTierPolicyDefinition,
    ConfidenceHandling,
    ModelCapabilitiesRequirement,
    ModelCatalogPublishReceipt,
    ModelCatalogUpdate,
    ModelFallbackPolicy,
    ModelRoutePolicy,
    ModelRoutingSnapshot,
    TierAuthority,
    TierBudgetRequirement,
    TierDecision,
    TierFallbackEdge,
    TierPolicyDefinition,
    TierSelectionContext,
    validate_routing_snapshot,
    validate_tier_authority,
)

__all__ = [
    "AdmissionDisposition",
    "BootstrapTierDecision",
    "BootstrapTierPolicyDefinition",
    "ConfidenceHandling",
    "EndpointAdmissionRequest",
    "EndpointAdmissionResult",
    "EndpointCapacityLease",
    "EndpointCapacityReceipt",
    "EndpointHealthStatus",
    "EndpointLoadSnapshot",
    "EndpointRejection",
    "EndpointRouteCandidatePlan",
    "EndpointTrafficPolicy",
    "ConservativeModelInvocationEstimator",
    "DeterministicModelTierPolicy",
    "InMemoryModelAdmissionController",
    "InMemoryModelOperationalStateRegistry",
    "InMemoryModelRoutingRegistry",
    "FixedPerceptionBootstrapTierPolicy",
    "LoadCounterScope",
    "ModelCapabilities",
    "ModelCapabilitiesRequirement",
    "ModelCatalogPublishReceipt",
    "ModelCatalogUpdate",
    "ModelEndpointDescriptor",
    "ModelEndpointHealth",
    "ModelEndpointRef",
    "ModelFailureKind",
    "ModelFallbackPolicy",
    "ModelInput",
    "ModelInputModality",
    "ModelInputPart",
    "ModelInvocationError",
    "ModelInvocationEstimate",
    "ModelOperationalSnapshot",
    "ModelOutputModality",
    "ModelPrivacyPolicy",
    "ModelProcessingBoundary",
    "ModelProcessingReceipt",
    "ModelProviderDescriptor",
    "ModelProviderError",
    "ModelProviderHealth",
    "ModelRequest",
    "ModelResponse",
    "ModelRetentionMode",
    "ModelRole",
    "ModelRoutePolicy",
    "ModelRoutingSnapshot",
    "ModelTier",
    "ModelTokenPricing",
    "ModelUsage",
    "ProviderRequest",
    "ProviderResponse",
    "ReasoningDepth",
    "ReasoningProfile",
    "RouteAttempt",
    "RouteAttemptKind",
    "RouteDecision",
    "RouteHint",
    "SafetyAnnotation",
    "StaleSnapshotPolicy",
    "StructuredOutputSupport",
    "StaticModelRouter",
    "TierAuthority",
    "TierBudgetRequirement",
    "TierDecision",
    "TierFallbackEdge",
    "TierPolicyDefinition",
    "TierSelectionContext",
    "bootstrap_tier_decision_digest",
    "bootstrap_tier_policy_definition_digest",
    "bootstrap_tier_selection_fingerprint",
    "endpoint_admission_request_digest",
    "endpoint_admission_result_digest",
    "endpoint_capacity_receipt_digest",
    "model_endpoint_descriptor_digest",
    "model_invocation_estimate_digest",
    "model_invocation_estimate_fingerprint",
    "model_operational_snapshot_digest",
    "model_request_digest",
    "model_request_fingerprint",
    "model_route_policy_digest",
    "model_error_info",
    "provider_request_digest",
    "route_decision_digest",
    "route_plan_fingerprint",
    "routing_catalog_digest",
    "task_complexity_assessment_digest",
    "task_complexity_assessment_fingerprint",
    "tier_authority_digest",
    "tier_decision_digest",
    "tier_policy_definition_digest",
    "tier_selection_context_digest",
    "tier_selection_fingerprint",
    "validate_routing_snapshot",
    "validate_tier_authority",
    "validate_bootstrap_tier_decision",
    "validate_tier_decision",
]

_IMPLEMENTATION_EXPORTS = {
    "ConservativeModelInvocationEstimator": ".estimation",
    "InMemoryModelAdmissionController": ".admission",
    "InMemoryModelOperationalStateRegistry": ".registry",
    "InMemoryModelRoutingRegistry": ".registry",
    "ModelTokenPricing": ".estimation",
    "StaticModelRouter": ".router",
    "DeterministicModelTierPolicy": ".tiering",
    "FixedPerceptionBootstrapTierPolicy": ".tiering",
    "validate_bootstrap_tier_decision": ".tiering",
    "validate_tier_decision": ".tiering",
}


def __getattr__(name: str) -> object:
    module_name = _IMPLEMENTATION_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    return getattr(import_module(module_name, __name__), name)


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
